
server:

  port: 10032


spring:
  datasource:
    url: jdbc:mysql://192.168.77.2:10227/birdReserveDatabase?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 20
      # 最小空闲连接数
      minimum-idle: 5
      # 连接超时时间（毫秒）
      connection-timeout: 15000
      # 空闲连接超时时间（毫秒）
      idle-timeout: 600000
      # 连接最大生存时间（毫秒）
      max-lifetime: 1800000
  
  redis:
    host: 192.168.77.2
    port: 10228
    password: 
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 15000  # 增加Redis超时时间到15秒，与RestTemplate一致
    
  # Jackson配置
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    default-property-inclusion: non_null

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.scenic.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# PageHelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 小程序端配置
miniapp:
  api:
    prefix: /api/uniapp
  security:
    jwt:
      secret: miniapp_secret_key_with_at_least_256_bits_for_hmac_sha_algorithm_security_requirement_rfc7518
      expiration: 86400000 # 24小时

# 管理后台端配置
admin:
  api:
    prefix: /api/manage
  security:
    jwt:
      secret: admin_secret_key_with_at_least_256_bits_for_hmac_sha_algorithm_security_requirement_rfc7518
      expiration: 7200000 # 2小时

# 日志配置
logging:
  level:
    com.scenic: debug
    com.scenic.mapper: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 文件上传配置
file:
  upload:
    max-file-size: 10MB
    max-request-size: 10MB

# MinIO配置
minio:
  endpoint: http://106.14.46.254:10029
  access-key: admin
  secret-key: zssg0325
  bucket-name: user-avatars
  photo-checkin-bucket: photo-checkin
  content-management-video-bucket: content-management
  content-management-audio-bucket: content-management-audio
  content-management-photo-bucket: content-management-photo
  files-bucket: files

# 微信小程序配置
wechat:
  miniapp:
    appId: wx78d1148e7f4afff9  # 实际的小程序AppID
    appSecret: 426d87b3961af6093b8d1beb66d2c141  # 实际的小程序AppSecret
    code2SessionUrl: https://api.weixin.qq.com/sns/jscode2session
